volumes:
  ui_node_modules:

services:
  backend:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    environment:
      PYTHONUNBUFFERED: "1"
      FRONTEND_ORIGINS: ${FRONTEND_ORIGINS:-http://localhost:${FRONTEND_PORT:-3003}}
      DEV_BACKEND_HTTP: ${DEV_BACKEND_HTTP:-http://localhost:${BACKEND_HOST_PORT:-5000}}
      DEV_BACKEND_WS: ${DEV_BACKEND_WS:-ws://localhost:${BACKEND_HOST_PORT:-5000}}
      CORS_ALLOW_METHODS: ${CORS_ALLOW_METHODS:-GET,POST,PUT,PATCH,DELETE,OPTIONS}
      CSP_CONNECT_EXTRAS: ${CSP_CONNECT_EXTRAS:-}
    ports:
      - "${BACKEND_HOST_PORT:-5000}:${BACKEND_CONTAINER_PORT:-8000}"
    volumes:
      - ./apps/backend:/app:rw
    command: >
      sh -lc "uvicorn main:app --host 0.0.0.0 --port ${BACKEND_CONTAINER_PORT:-8000}
      --reload --reload-exclude setup.py"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').status==200 else sys.exit(1)"]
      interval: 5s
      timeout: 2s
      retries: 15
      start_period: 10s

  frontend:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ./apps/ui
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      NODE_ENV: development                         # ✅ fix Next warning
      APP_ENV: ${APP_ENV:-local}                    # optional custom env flag
      FRONTEND_PORT: ${FRONTEND_PORT:-3003}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://localhost:${BACKEND_HOST_PORT:-5000}}
      BACKEND_INTERNAL_URL: ${BACKEND_INTERNAL_URL:-http://backend:${BACKEND_CONTAINER_PORT:-8000}}
    command: sh -lc "npm run dev -- -p ${FRONTEND_PORT:-3003}"
    ports:
      - "${FRONTEND_PORT:-3003}:${FRONTEND_PORT:-3003}"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./apps/ui:/app:rw
      - ui_node_modules:/app/node_modules
