# docker-compose.yml

version: "3.8"

volumes:
  ui_node_modules:

services:
  frontend:
    build:
      context: ./apps/ui
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    depends_on:
      - backend
    volumes:
      - ./apps/ui:/app:rw
      - ui_node_modules:/app/node_modules   # <- keep deps visible

  backend:
    build:
      context: ./apps/backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app:rw
    environment:
      - PYTHONUNBUFFERED=1
