# apps/backend/Dockerfile

# syntax=docker/dockerfile:1.7
FROM python:3.10-slim
WORKDIR /app

COPY requirements.txt .
ENV PIP_NO_CACHE_DIR=1
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

COPY . .
EXPOSE 8000
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000","--reload"]
